import type { WorkoutSessionEvent } from "./workout-session-events";

export type AttemptPrescription = { schemaVersion: number; prescribedWorkMs: number; prescribedRestMs: number; prescribedTotalMs: number; steps: { workoutExerciseId: string; position: number; workMs: number; restMs: number }[] };
export type AttemptIssue = "missing_workout_start" | "missing_workout_complete" | "sequence_gap" | "duplicate_sequence" | "invalid_start_structure" | "invalid_terminal_structure" | "terminal_not_last" | "invalid_step_reference" | "invalid_position" | "invalid_phase_duration" | "unpaired_pause" | "unpaired_visibility" | "non_monotonic_elapsed" | "duplicate_phase_transition" | "completion_skip_conflict" | "unobserved_phase_progress" | "unsupported_prescription_version" | "missing_result";
export type AttemptQuality = "partial" | "complete" | "reconstructed" | "unknown";
export type AttemptSummary = { quality: AttemptQuality; finalizationEligible: boolean; issues: AttemptIssue[]; elapsedAttemptMs: number | null; explicitPauseMs: number | null; workTimerProgressedMs: number | null; restTimerProgressedMs: number | null; hiddenMs: number | null; completedWorkBlocks: number; skippedWorkBlocks: number; completedRestBlocks: number; skippedRestBlocks: number; firstSequence: number | null; lastSequence: number | null; eventCount: number };
const unknownIssues = new Set<AttemptIssue>(["duplicate_sequence","invalid_start_structure","invalid_terminal_structure","terminal_not_last","invalid_step_reference","invalid_position","invalid_phase_duration","non_monotonic_elapsed","duplicate_phase_transition","completion_skip_conflict"]);

export function summarizeWorkoutAttempt(prescription: AttemptPrescription, events: WorkoutSessionEvent[], hasCanonicalResult: boolean): AttemptSummary {
  const issues = new Set<AttemptIssue>(); const ordered = [...events].sort((a,b) => a.sequence-b.sequence || a.id.localeCompare(b.id));
  if (prescription.schemaVersion !== 1 || prescription.prescribedTotalMs !== prescription.prescribedWorkMs + prescription.prescribedRestMs) issues.add("unsupported_prescription_version");
  let previousSequence: number | null = null, previousElapsed: number | null = null, pauseStart: number | null = null, hiddenStart: number | null = null, pause = 0, hidden = 0, starts = 0, terminals = 0;
  const completedWork = new Set<string>(), skippedWork = new Set<string>(), completedRest = new Set<string>(), skippedRest = new Set<string>();
  for (const [index,event] of ordered.entries()) {
    if (event.sequence === previousSequence) issues.add("duplicate_sequence"); else if (previousSequence !== null && event.sequence !== previousSequence + 1) issues.add("sequence_gap");
    if (previousElapsed !== null && event.elapsed_ms < previousElapsed) issues.add("non_monotonic_elapsed"); previousSequence=event.sequence; previousElapsed=event.elapsed_ms;
    if (event.event_type === "workout_started") { starts++; if (starts !== 1) issues.add("duplicate_phase_transition"); if (event.sequence !== 0 || event.phase !== "ready" || event.workout_exercise_id !== null || event.step_position !== null || event.phase_duration_ms !== null || event.phase_elapsed_ms !== null) issues.add("invalid_start_structure"); }
    if (event.event_type === "workout_completed") { terminals++; if (terminals !== 1) issues.add("duplicate_phase_transition"); if (index !== ordered.length-1) issues.add("terminal_not_last"); if (event.phase !== "finished" || event.workout_exercise_id !== null || event.step_position !== null || event.phase_duration_ms !== null || event.phase_elapsed_ms !== null) issues.add("invalid_terminal_structure"); }
    const timed=event.phase === "work" || event.phase === "rest"; const step=event.workout_exercise_id === null ? null : prescription.steps.find((item)=>item.workoutExerciseId===event.workout_exercise_id);
    if (timed && (!step || event.step_position === null || event.phase_duration_ms === null || event.phase_elapsed_ms === null)) issues.add("invalid_step_reference");
    if (!timed && (event.workout_exercise_id !== null || event.step_position !== null || event.phase_duration_ms !== null || event.phase_elapsed_ms !== null)) issues.add(event.event_type === "workout_started" ? "invalid_start_structure" : "invalid_terminal_structure");
    if (event.workout_exercise_id !== null && !step) issues.add("invalid_step_reference"); if (step && event.step_position !== step.position) issues.add("invalid_position"); if (step && (event.phase_duration_ms !== (event.phase === "work" ? step.workMs : step.restMs) || (event.phase_elapsed_ms !== null && event.phase_duration_ms !== null && event.phase_elapsed_ms > event.phase_duration_ms))) issues.add("invalid_phase_duration");
    if (event.event_type === "timer_paused") { if (pauseStart !== null) issues.add("unpaired_pause"); else pauseStart=event.elapsed_ms; }
    if (event.event_type === "timer_resumed") { if (pauseStart === null) issues.add("unpaired_pause"); else { pause+=event.elapsed_ms-pauseStart; pauseStart=null; } }
    if (event.event_type === "page_hidden") { if (hiddenStart !== null) issues.add("unpaired_visibility"); else hiddenStart=event.elapsed_ms; }
    if (event.event_type === "page_visible") { if (hiddenStart === null) issues.add("unpaired_visibility"); else { hidden+=event.elapsed_ms-hiddenStart; hiddenStart=null; } }
    if (step && event.event_type === "exercise_completed") completedWork.add(step.workoutExerciseId); if (step && event.event_type === "exercise_skipped") skippedWork.add(step.workoutExerciseId); if (step && event.event_type === "rest_completed") completedRest.add(step.workoutExerciseId); if (step && event.event_type === "rest_skipped") skippedRest.add(step.workoutExerciseId);
  }
  if (!starts) issues.add("missing_workout_start"); if (!terminals) issues.add("missing_workout_complete"); if (!hasCanonicalResult) issues.add("missing_result"); if (pauseStart !== null) issues.add("unpaired_pause"); if (hiddenStart !== null) issues.add("unpaired_visibility");
  if ([...completedWork].some((id)=>skippedWork.has(id)) || [...completedRest].some((id)=>skippedRest.has(id))) issues.add("completion_skip_conflict");
  const terminalElapsed=ordered.at(-1)?.event_type === "workout_completed" ? ordered.at(-1)?.elapsed_ms ?? null : null; if (terminalElapsed !== null && terminalElapsed-pause > prescription.prescribedTotalMs) issues.add("unobserved_phase_progress");
  const quality: AttemptQuality=[...issues].some((issue)=>unknownIssues.has(issue)) ? "unknown" : issues.size ? "partial" : "complete"; const complete=quality === "complete";
  return {quality,finalizationEligible:complete && hasCanonicalResult,issues:[...issues].sort(),elapsedAttemptMs:complete?terminalElapsed:null,explicitPauseMs:complete?pause:null,workTimerProgressedMs:null,restTimerProgressedMs:null,hiddenMs:complete?hidden:null,completedWorkBlocks:completedWork.size,skippedWorkBlocks:skippedWork.size,completedRestBlocks:completedRest.size,skippedRestBlocks:skippedRest.size,firstSequence:ordered[0]?.sequence ?? null,lastSequence:ordered.at(-1)?.sequence ?? null,eventCount:ordered.length};
}
