import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import vm from "node:vm";
import test from "node:test";
import ts from "typescript";
import { indexedDB } from "fake-indexeddb";
import * as React from "react";
import { renderToStaticMarkup } from "react-dom/server";
const require = createRequire(import.meta.url);
function load(path, mocks = {}) {
 const code = ts.transpileModule(readFileSync(new URL("../"+path,import.meta.url),"utf8"),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 const loaded = {exports:{}}; new vm.Script(`(function(require,module,exports){${code}\n})`).runInThisContext()((name)=>name in mocks?mocks[name]:require(name),loaded,loaded.exports); return loaded.exports;
}
const state = load("src/lib/workout-session-state.ts");
const completion = load("src/lib/complete-training-session.ts");
const finalization = load("src/lib/workout-attempt-finalization.ts");
const prescriptionMapper = load("src/lib/training-session-prescription.ts");
const events = load("src/lib/workout-session-events.ts");
globalThis.indexedDB = indexedDB;
const storage = load("src/lib/workout-session-storage.ts", {"./workout-session-state":state,"./workout-session-events":events});
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
let next=100; const uuid=()=>id(next++); const start=Date.parse("2026-09-14T12:00:00.000Z");
const step=(changes={})=>({id:id(4),position:0,exerciseName:"Cradle",durationSeconds:10,restSeconds:5,offHand:false,notes:null,videoUrl:null,...changes});
const input={actorUserId:id(1),athleteId:id(1),sessionId:id(2),workoutId:id(3),workoutName:"Test",steps:[step(),step({id:id(5),position:1,durationSeconds:20,restSeconds:0})]};
const begin=(changes={})=>state.beginAttempt({...input,...changes},start,uuid);
const command=(cp,c,ms,observed=true)=>state.changeAttempt(cp,c,start+ms,uuid,observed);
for (const [name,ms,phase,index,remaining] of [
 ["normal countdown",3000,"work",0,7000], ["work expires",10000,"rest",0,5000],
 ["rest expires",15000,"work",1,20000], ["long delay",22000,"work",1,13000],
 ["all deadlines missed",60000,"finished",1,0],
]) test(name,()=>{const change=command(begin().checkpoint,"tick",ms);assert.equal(change.checkpoint.phase,phase);assert.equal(change.checkpoint.index,index);assert.equal(state.remainingMs(change.checkpoint,start+ms),remaining);});
test("no rest advances directly",()=>{const cp=begin({steps:[step({restSeconds:0}),step({id:id(5)})]}).checkpoint;assert.equal(command(cp,"tick",10000).checkpoint.index,1);});
test("timely expiration emits paired transitions",()=>{assert.deepEqual(command(begin().checkpoint,"tick",10000).events.map(e=>e.event_type),["exercise_completed","rest_started"]);});
test("rest timely expiration emits completion then work start",()=>{const cp=command(begin().checkpoint,"tick",10000).checkpoint;assert.deepEqual(command(cp,"tick",15000).events.map(e=>e.event_type),["rest_completed","exercise_started"]);});
test("late recovery emits no fabricated expiration events",()=>{const c=command(begin().checkpoint,"recover",22000);assert.equal(c.events.length,0);assert.equal(c.checkpoint.inferredTransitions,2);});
test("long delay is bounded and emits no burst",()=>{const c=command(begin().checkpoint,"tick",86400000);assert.equal(c.events.length,0);assert.equal(c.checkpoint.phase,"finished");});
test("repeated tick/recovery cannot duplicate transitions",()=>{const c=command(begin().checkpoint,"tick",10000);assert.equal(command(c.checkpoint,"tick",10000).events.length,0);assert.equal(command(c.checkpoint,"recover",10000).events.length,0);});
test("explicit pause freezes even after long delay",()=>{const c=command(begin().checkpoint,"pause",3000);assert.equal(c.events[0].event_type,"timer_paused");assert.equal(state.remainingMs(command(c.checkpoint,"tick",60000).checkpoint,start+60000),7000);});
test("resume keeps correct remaining and pause metrics",()=>{const cp=command(begin().checkpoint,"pause",3000).checkpoint;const c=command(cp,"resume",13000);assert.equal(c.events[0].event_type,"timer_resumed");assert.equal(state.remainingMs(c.checkpoint,start+13000),7000);assert.equal(c.checkpoint.totalPauseMs,10000);});
test("duplicate explicit pause/resume are no-ops",()=>{let cp=command(begin().checkpoint,"pause",3000).checkpoint;assert.equal(command(cp,"pause",4000).events.length,0);cp=command(cp,"resume",5000).checkpoint;assert.equal(command(cp,"resume",6000).events.length,0);});
test("skip work records timing and retains rest",()=>{const c=command(begin().checkpoint,"skip",3000);assert.deepEqual(c.events.map(e=>e.event_type),["exercise_skipped","rest_started"]);assert.equal(c.events[0].phase_elapsed_ms,3000);assert.equal(c.checkpoint.skippedSteps,1);assert.equal(c.checkpoint.workProgressMs,3000);});
test("skipped work does not become completed",()=>{const c=command(begin().checkpoint,"skip",3000);assert.equal(command(c.checkpoint,"tick",8000).events.some(e=>e.event_type==="exercise_completed"),false);});
test("rest skip advances once",()=>{const cp=command(begin().checkpoint,"skip",3000).checkpoint;const c=command(cp,"skip",4000);assert.deepEqual(c.events.map(e=>e.event_type),["rest_skipped","exercise_started"]);assert.equal(c.checkpoint.index,1);});
test("skip at expiration does not skip newly entered phase",()=>{const c=command(begin().checkpoint,"skip",10000);assert.equal(c.checkpoint.phase,"rest");assert.equal(c.events.some(e=>e.event_type==="rest_skipped"),false);});
test("start identity and sequence emitted once",()=>{const b=begin();assert.ok(b.checkpoint.attemptId);assert.deepEqual(b.events.map(e=>e.event_type),["workout_started","exercise_started"]);assert.deepEqual(b.events.map(e=>e.sequence),[0,1]);assert.equal(command(b.checkpoint,"recover",3000).checkpoint.attemptId,b.checkpoint.attemptId);});
test("checkpoint recovery uses saved anchors",()=>{const cp=command(begin().checkpoint,"tick",3000).checkpoint;cp.savedWallAt=start+3000;const now=state.recoveryNow(cp,start+5000);assert.equal(state.remainingMs(command(cp,"recover",now-start).checkpoint,now),5000);});
test("clock backwards/huge jumps cannot create negative elapsed",()=>{const cp=begin().checkpoint;assert.equal(state.recoveryNow(cp,start-100000),start);assert.equal(state.recoveryNow(cp,start+86400001),start);assert.equal(command(cp,"tick",-100).checkpoint.logicalNow,start);});
test("pause remains paused after refresh",()=>{const cp=command(begin().checkpoint,"pause",3000).checkpoint;assert.equal(command(cp,"recover",30000).checkpoint.pausedAt,start+3000);});
test("visibility context does not pause or change deadline",()=>{const cp=begin().checkpoint;const hidden=command(cp,"hidden",3000,false);assert.equal(hidden.events[0].event_type,"page_hidden");assert.equal(hidden.checkpoint.phaseStartedAt,cp.phaseStartedAt);assert.equal(hidden.checkpoint.pausedAt,null);const visible=command(hidden.checkpoint,"visible",13000,false);assert.equal(visible.checkpoint.phase,"rest");assert.equal(visible.events.at(-1).event_type,"page_visible");});
test("finalization emits once then no visibility or recovery events",()=>{const c=command(begin().checkpoint,"finalize",35000);assert.equal(c.events.at(-1).event_type,"workout_completed");for(const name of ["hidden","visible","recover","finalize"]){assert.equal(command(c.checkpoint,name,40000).events.length,0);}});
test("visibility after guidance reaches finished cannot emit an invalid finished-phase event",()=>{const cp=command(begin().checkpoint,"tick",60000).checkpoint;assert.equal(cp.phase,"finished");assert.equal(cp.finalized,false);for(const commandName of ["hidden","visible"]){assert.equal(command(cp,commandName,61000,false).events.length,0);}});
test("generated events conform to endpoint vocabulary/structure",()=>{let cp=begin().checkpoint;for(const [c,ms] of [["pause",1000],["resume",2000],["skip",3000],["hidden",4000],["visible",5000],["skip",6000],["finalize",30000]]){const result=command(cp,c,ms);events.parseEventBatch({events:result.events});cp=result.checkpoint;}});

test("real IndexedDB checkpoint and events persist atomically before delivery",async()=>{const b=begin();await storage.mutateBundle(input.athleteId,bundle=>storage.saveChange(bundle,b,start));const loaded=await storage.mutateBundle(input.athleteId,()=>{});assert.equal(loaded.checkpoints[input.sessionId].attemptId,b.checkpoint.attemptId);assert.equal(loaded.outbox.length,2);});
test("another athlete cannot load checkpoint/outbox",async()=>{const b=await storage.mutateBundle(id(900),()=>{});assert.equal(b.outbox.length,0);assert.equal(b.checkpoints[input.sessionId],undefined);});
test("two serialized begins persist one attempt",async()=>{const athleteId=id(901);await Promise.all([1,2].map(()=>storage.mutateBundle(athleteId,bundle=>{if(!bundle.checkpoints[input.sessionId])storage.saveChange(bundle,begin({athleteId}),start);})));const b=await storage.mutateBundle(athleteId,()=>{});assert.equal(b.outbox.length,2);});
test("same actor can retain isolated checkpoints and attempts for two athletes",async()=>{const actorUserId=id(910),childA=id(911),childB=id(912),sessionA=id(913),sessionB=id(914);const a=begin({athleteId:childA,sessionId:sessionA});const b=begin({athleteId:childB,sessionId:sessionB});await storage.mutateBundle(childA,bundle=>storage.saveChange(bundle,a,start));await storage.mutateBundle(childB,bundle=>storage.saveChange(bundle,b,start));const storedA=await storage.mutateBundle(childA,()=>{}),storedB=await storage.mutateBundle(childB,()=>{});assert.equal(actorUserId,id(910));assert.equal(storedA.checkpoints[sessionA].attemptId,a.checkpoint.attemptId);assert.equal(storedA.checkpoints[sessionB],undefined);assert.equal(storedB.checkpoints[sessionB].attemptId,b.checkpoint.attemptId);assert.equal(storedB.checkpoints[sessionA],undefined);});
test("flushing one athlete acknowledges no sibling outbox events",async()=>{const actorUserId=id(920),childA=id(921),childB=id(922),sessionA=id(923),sessionB=id(924);const a=begin({athleteId:childA,sessionId:sessionA}),b=begin({athleteId:childB,sessionId:sessionB});await storage.mutateBundle(childA,bundle=>storage.saveChange(bundle,a,start));await storage.mutateBundle(childB,bundle=>storage.saveChange(bundle,b,start));const original=globalThis.fetch;try{globalThis.fetch=async(_url,opts)=>new Response(JSON.stringify({acknowledgements:JSON.parse(opts.body).events.map(e=>({id:e.id,status:"accepted"}))}));await storage.flushEvents(childA,actorUserId,async()=>actorUserId);assert.equal((await storage.mutateBundle(childA,()=>{})).outbox.length,0);assert.equal((await storage.mutateBundle(childB,()=>{})).outbox.length,2);}finally{globalThis.fetch=original;}});
test("finalizing one athlete checkpoint cannot alter a sibling checkpoint",async()=>{const childA=id(930),childB=id(931),sessionA=id(932),sessionB=id(933);const a=begin({athleteId:childA,sessionId:sessionA}),b=begin({athleteId:childB,sessionId:sessionB});await storage.mutateBundle(childA,bundle=>storage.saveChange(bundle,a,start));await storage.mutateBundle(childB,bundle=>storage.saveChange(bundle,b,start));await storage.mutateBundle(childA,bundle=>storage.saveChange(bundle,command(bundle.checkpoints[sessionA],"finalize",35000),start+35000));assert.equal((await storage.mutateBundle(childA,()=>{})).checkpoints[sessionA].finalized,true);assert.equal((await storage.mutateBundle(childB,()=>{})).checkpoints[sessionB].finalized,false);});
test("same-UUID legacy bundle migrates deterministically to athlete storage",()=>{const legacyAttempt=begin({athleteId:input.athleteId});const legacy={userId:input.athleteId,checkpoints:{[input.sessionId]:{...legacyAttempt.checkpoint,userId:input.athleteId,athleteId:undefined}},outbox:legacyAttempt.events.map(event=>({event,status:"pending"})),dropped:0};const migrated=storage.migrateLegacyBundle(input.athleteId,legacy);assert.equal(migrated.athleteId,input.athleteId);assert.equal(migrated.checkpoints[input.sessionId].athleteId,input.athleteId);assert.equal("userId" in migrated.checkpoints[input.sessionId],false);assert.equal(migrated.outbox.length,2);assert.deepEqual(storage.migrateLegacyBundle(input.athleteId,legacy),migrated);});
test("ambiguous parent-keyed legacy bundle never attaches to a child",()=>{const parent=id(940),child=id(941);const legacy={userId:parent,checkpoints:{},outbox:[],dropped:0};assert.equal(storage.migrateLegacyBundle(child,legacy),undefined);});
test("outbox batch respects 25-event limit",()=>{const b={outbox:Array.from({length:30},(_,n)=>({event:begin().events[0],status:"pending",n}))};assert.equal(storage.eventBatch(b).length,25);});
test("outbox capacity bounded, existing errors preserved",()=>{const b={checkpoints:{},outbox:Array(2500).fill({status:"conflict",event:begin().events[0]}),dropped:0};storage.saveChange(b,begin(),start);assert.equal(b.outbox.length,2500);assert.equal(b.dropped,2);});
for(const status of ["accepted","duplicate","conflict","rejected","retry","unknown"])test("acknowledgement "+status,()=>{const e=begin().events[0];const b={outbox:[{event:e,status:"pending"}]};storage.acknowledge(b,[e],{acknowledgements:[{id:e.id,status}]});assert.equal(b.outbox.length,["accepted","duplicate"].includes(status)?0:1);if(["conflict","rejected"].includes(status))assert.equal(b.outbox[0].status,status);});
test("malformed or foreign acknowledgements leave queue unchanged",()=>{const e=begin().events[0];const b={outbox:[{event:e,status:"pending"}]};for(const payload of [null,{}, {acknowledgements:[null,{id:id(999),status:"accepted"}]}])storage.acknowledge(b,[e],payload);assert.equal(b.outbox.length,1);});
test("failed send retries exact UUID/payload then acknowledgement removes",async()=>{const athleteId=id(902),actorUserId=id(90);await storage.mutateBundle(athleteId,b=>storage.saveChange(b,begin({athleteId}),start));const originalFetch=globalThis.fetch;const bodies=[];try{globalThis.fetch=async(_url,opts)=>{bodies.push(opts.body);throw Error("offline");};await storage.flushEvents(athleteId,actorUserId,async()=>actorUserId);await storage.flushEvents(athleteId,actorUserId,async()=>actorUserId);assert.equal(bodies[0],bodies[1]);globalThis.fetch=async(_url,opts)=>new Response(JSON.stringify({acknowledgements:JSON.parse(opts.body).events.map(e=>({id:e.id,status:"accepted"}))}));await storage.flushEvents(athleteId,actorUserId,async()=>actorUserId);assert.equal((await storage.mutateBundle(athleteId,()=>{})).outbox.length,0);}finally{globalThis.fetch=originalFetch;}});
test("attempt registration callback receives only a durably acknowledged start with its original UUID",async()=>{const athleteId=id(903),actorUserId=id(90);const started=begin({athleteId});await storage.mutateBundle(athleteId,b=>storage.saveChange(b,started,start));const original=globalThis.fetch;const acknowledged=[];try{globalThis.fetch=async(_url,opts)=>new Response(JSON.stringify({acknowledgements:JSON.parse(opts.body).events.map(e=>({id:e.id,status:"accepted"}))}));await storage.flushEvents(athleteId,actorUserId,async()=>actorUserId,events=>acknowledged.push(...events.filter(e=>e.event_type==="workout_started")));assert.equal(acknowledged.length,1);assert.equal(acknowledged[0].attempt_id,started.checkpoint.attemptId);assert.equal(acknowledged[0].sequence,0);}finally{globalThis.fetch=original;}});
test("attempt RPC integration sends only identity parameters",()=>{const source=readFileSync(new URL("../src/components/workout/use-workout-session.ts",import.meta.url),"utf8");const helper=readFileSync(new URL("../src/lib/workout-attempt-finalization.ts",import.meta.url),"utf8");assert.match(source,/register_my_workout_session_attempt", \{ p_attempt_id: attemptId, p_session_id: input\.sessionId \}/);assert.match(source,/finalizePersistedWorkoutAttempt\(supabase, input\.sessionId, cp\.attemptId\)/);assert.match(helper,/finalize_my_workout_session_attempt",\s*\{ p_attempt_id: attemptId \}/);assert.doesNotMatch(helper,/p_summary|started_at|elapsed_attempt_ms|measurement_quality/);});
function finalizationClient(options={}) {
 const calls=[];const query={select(){return query;},eq(column,value){calls.push({type:"event",column,value});return query;},then(resolve){return Promise.resolve({data:options.eventExists===false?[]:[{id:id(700)}],error:options.eventError?{message:"offline"}:null}).then(resolve);}};
 return {calls,client:{from(table){assert.equal(table,"workout_session_events");return query;},rpc:async(name,args)=>{calls.push({type:"rpc",name,args});return {error:options.rpcError?{message:"offline"}:null};}}};
}
test("attempt finalization waits for persisted terminal telemetry and sends only attempt identity",async()=>{const f=finalizationClient();await finalization.finalizePersistedWorkoutAttempt(f.client,input.sessionId,id(701));assert.deepEqual(f.calls.at(-1),{type:"rpc",name:"finalize_my_workout_session_attempt",args:{p_attempt_id:id(701)}});assert.equal(f.calls.filter(call=>call.type==="event").length,3);});
test("missing terminal telemetry prevents finalization RPC",async()=>{const f=finalizationClient({eventExists:false});await assert.rejects(finalization.finalizePersistedWorkoutAttempt(f.client,input.sessionId,id(702)),/not persisted/);assert.equal(f.calls.some(call=>call.type==="rpc"),false);});
test("failed attempt finalization remains retryable without another canonical completion",async()=>{const failed=finalizationClient({rpcError:true});await assert.rejects(finalization.finalizePersistedWorkoutAttempt(failed.client,input.sessionId,id(703)),/needs retry/);const retry=finalizationClient();await finalization.finalizePersistedWorkoutAttempt(retry.client,input.sessionId,id(703));assert.equal(retry.calls.filter(call=>call.type==="rpc").length,1);});
test("completed delivery retries finalization for an already-finalized checkpoint",()=>{const source=readFileSync(new URL("../src/components/workout/completed-workout-delivery.tsx",import.meta.url),"utf8");assert.match(source,/finalizePersistedWorkoutAttempt\(client, sessionId, checkpoint\.attemptId\)/);assert.match(source,/window\.setInterval\(\(\) => \{ void finish\(\); \}, 30000\)/);});
test("server-loaded durable athlete identity is required for browser persistence",()=>{const page=readFileSync(new URL("../src/app/training/[sessionId]/page.tsx",import.meta.url),"utf8");const player=readFileSync(new URL("../src/components/workout/workout-player.tsx",import.meta.url),"utf8");assert.match(page,/athlete_id,/);assert.match(page,/athleteId=\{session\.athlete_id\}/);assert.match(page,/!session\.athlete_id/);assert.doesNotMatch(player,/athleteId=\{user\.id\}/);});
test("wrong signed-in actor never transmits queued events",async()=>{let called=false;const original=globalThis.fetch;try{globalThis.fetch=async()=>{called=true;};await storage.flushEvents(input.athleteId,input.actorUserId,async()=>id(999));assert.equal(called,false);}finally{globalThis.fetch=original;}});
const video=load("src/components/workout/exercise-video.tsx");
test("video is muted inline looping visual media",()=>{const html=renderToStaticMarkup(React.createElement(video.default,{url:"https://example.com/demo.mp4"}));for(const flag of ["muted","loop","playsInline","autoPlay"])assert.ok(html.toLowerCase().includes(flag.toLowerCase()));});
test("missing/unsafe video leaves workout unaffected",()=>{assert.equal(video.safeVideoUrl("javascript:alert(1)"),null);assert.equal(renderToStaticMarkup(React.createElement(video.default,{url:null})),"");});
test("video component has no timer coupling or playback telemetry",()=>{const source=readFileSync(new URL("../src/components/workout/exercise-video.tsx",import.meta.url),"utf8");assert.doesNotMatch(source,/changeAttempt|run\(|flushEvents|workout-session-events/);});
function findButton(tree, label) {
 if(!tree||typeof tree!=="object")return null;
 if(tree.type==="button" && tree.props.children===label)return tree;
 const children=tree.props?.children;
 for(const child of Array.isArray(children)?children:[children]) {const found=findButton(child,label);if(found)return found;}return null;
}
function completionSetup(options={}) {
 const cp=command(begin().checkpoint,"recover",35000).checkpoint;const calls=[];let rpcCalls=0;
 const client={auth:{getUser:async()=>({data:{user:{id:options.wrongUser?id(999):input.actorUserId}},error:null})},from(){
  const q={select(){return q;},eq(){return q;},single(){return q;},limit(){return q;},then(resolve){return Promise.resolve({data:[],error:null}).then(resolve);}};return q;
 },rpc:async(name,args)=>{rpcCalls++;calls.push({type:"result",name,args});if(options.rpcFailure)return {data:null,error:{message:"denied"}};return {data:[{result_id:id(800),already_completed:Boolean(options.completed)}],error:null}}};
 const fakeReact={...React,useMemo:fn=>fn(),useState:v=>[typeof v==="function"?v():v,()=>{}],useRef:v=>({current:v})};
 const player=load("src/components/workout/workout-player.tsx",{
  react:fakeReact,"next/navigation":{useRouter:()=>({push:path=>calls.push({type:"navigate",path}),refresh:()=>{}})},
  "@/lib/supabase/client":{createClient:()=>client},"@/lib/complete-training-session":{completeTrainingSession:async(client,sessionId)=>{const response=await client.rpc("complete_my_training_session",{p_session_id:sessionId});if(response.error)throw Error("Unable to save workout. Retry safely.");return {resultId:response.data[0].result_id,alreadyCompleted:response.data[0].already_completed};}},"@/lib/workout-session-state":state,
  "./use-workout-session":{useWorkoutSession:()=>({checkpoint:cp,ready:true,warning:"",run:async c=>{calls.push({type:c});if(options.telemetryFailure)throw Error("offline");},flush:async()=>{},finalizeAttempt:async()=>{calls.push({type:"materialize"});if(options.materializationFailure)throw Error("offline");}})},
  "./exercise-video":{default:()=>null,safeVideoUrl:url=>url},
 });
 const tree=player.default({...input,steps:input.steps});return {button:findButton(tree,"Finish workout"),calls,rpcCalls:()=>rpcCalls};
}
test("canonical RPC and completion telemetry precede attempt materialization",async()=>{const oldWindow=globalThis.window;globalThis.window={setTimeout:fn=>{fn();return 0;}};try{const s=completionSetup();await s.button.props.onClick();assert.deepEqual(s.calls.map(c=>c.type),["result","finalize","materialize","navigate"]);assert.deepEqual(s.calls[0].args,{p_session_id:input.sessionId});}finally{globalThis.window=oldWindow;}});
test("telemetry failure cannot block legitimate canonical completion",async()=>{const oldWindow=globalThis.window;globalThis.window={setTimeout:fn=>{fn();return 0;}};try{const s=completionSetup({telemetryFailure:true});await s.button.props.onClick();assert.equal(s.rpcCalls(),1);assert.equal(s.calls.at(-1).type,"navigate");}finally{globalThis.window=oldWindow;}});
test("attempt materialization failure cannot block legitimate canonical completion",async()=>{const oldWindow=globalThis.window;globalThis.window={setTimeout:fn=>{fn();return 0;}};try{const s=completionSetup({materializationFailure:true});await s.button.props.onClick();assert.equal(s.rpcCalls(),1);assert.equal(s.calls.at(-1).type,"navigate");}finally{globalThis.window=oldWindow;}});
test("already completed RPC result remains successful and retries materialization",async()=>{const oldWindow=globalThis.window;globalThis.window={setTimeout:fn=>{fn();return 0;}};try{const s=completionSetup({completed:true});await s.button.props.onClick();assert.equal(s.rpcCalls(),1);assert.deepEqual(s.calls.map(c=>c.type),["result","finalize","materialize","navigate"]);}finally{globalThis.window=oldWindow;}});
test("RPC failure prevents completion telemetry",async()=>{const s=completionSetup({rpcFailure:true});await s.button.props.onClick();assert.equal(s.rpcCalls(),1);assert.equal(s.calls.some(call=>call.type==="finalize"),false);});
test("wrong account cannot invoke canonical completion",async()=>{const s=completionSetup({wrongUser:true});await s.button.props.onClick();assert.equal(s.rpcCalls(),0);assert.equal(s.calls.length,0);});
test("concurrent Finish clicks produce one canonical RPC call",async()=>{const oldWindow=globalThis.window;globalThis.window={setTimeout:fn=>{fn();return 0;}};try{const s=completionSetup();await Promise.all([s.button.props.onClick(),s.button.props.onClick()]);assert.equal(s.rpcCalls(),1);}finally{globalThis.window=oldWindow;}});
test("player completion has no direct result INSERT or browser-owned result fields",()=>{const source=readFileSync(new URL("../src/components/workout/workout-player.tsx",import.meta.url),"utf8");assert.match(source,/completeTrainingSession\(supabase, sessionId\)/);assert.doesNotMatch(source,/from\("workout_results"\)\.insert|athlete_user_id: user\.id|started_at: new Date|completed_at: new Date|active_minutes:|total_duration_minutes:|exercises_completed:|result_data:/);});
test("canonical completion helper sends only session identity and accepts idempotency",async()=>{let args;const result=await completion.completeTrainingSession({rpc:async(name,value)=>{args={name,value};return {data:[{result_id:id(801),already_completed:true}],error:null};}},input.sessionId);assert.deepEqual(args,{name:"complete_my_training_session",value:{p_session_id:input.sessionId}});assert.deepEqual(result,{resultId:id(801),alreadyCompleted:true});});
test("canonical completion helper maps RPC failure to retry-safe UI error",async()=>{await assert.rejects(completion.completeTrainingSession({rpc:async()=>({data:null,error:{message:"database detail"}})},input.sessionId),/Unable to save workout\. Retry safely\./);});
test("video source changes cleanly with exercise reference",()=>{const first=renderToStaticMarkup(React.createElement(video.default,{url:"https://example.com/a.mp4"}));const second=renderToStaticMarkup(React.createElement(video.default,{url:"https://example.com/b.mp4"}));assert.notEqual(first,second);assert.ok(second.includes("b.mp4"));});

test("server prescription mapper rejects unsupported versions and preserves snapshot semantics",()=>{
 const row={workout_id:input.workoutId,workout_name:"Frozen",schema_version:1,prescribed_work_ms:10000,prescribed_rest_ms:5000,prescribed_total_ms:15000,step_count:1,steps:[{workout_exercise_id:id(4),exercise_id:id(55),exercise_name:"Frozen Exercise",position:0,work_ms:10000,rest_ms:5000,off_hand:true,notes:"Keep"}]};
 const mapped=prescriptionMapper.mapSessionPrescription(row,new Map([[id(4),"https://example.com/live.mp4"]]));
 assert.equal(mapped.workoutName,"Frozen");assert.deepEqual(mapped.steps[0],{id:id(4),position:0,exerciseName:"Frozen Exercise",durationSeconds:10,restSeconds:5,offHand:true,notes:"Keep",videoUrl:"https://example.com/live.mp4"});
 assert.throws(()=>prescriptionMapper.mapSessionPrescription({...row,schema_version:2},new Map()),/Unsupported/);
});
function pageSetup(options={}) {
 const actorUserId=options.actorUserId??(options.coach?id(50):input.actorUserId),athleteId=options.athleteId??input.athleteId;
 const queries={training_sessions:{id:input.sessionId,workout_id:input.workoutId,athlete_id:athleteId,athlete_user_id:options.athleteUserId??input.actorUserId,team_id:id(99),scheduled_date:"2026-09-14",status:options.completed?"completed":"scheduled",workouts:{id:input.workoutId,name:"Test"},teams:{id:id(99),name:"Team"}},workout_results:options.completed?[{id:id(100)}]:[],team_memberships:options.unauthorized?null:{role:"coach"},workout_exercises:[{id:id(4),position:0,duration_seconds:10,rest_seconds:5,off_hand:false,notes:null,exercises:{id:id(55),name:"Test",video_url:null}}],training_session_prescriptions:{workout_id:input.workoutId,workout_name:"Test",schema_version:1,prescribed_work_ms:10000,prescribed_rest_ms:5000,prescribed_total_ms:15000,step_count:1,steps:[{workout_exercise_id:id(4),exercise_id:id(55),exercise_name:"Snapshot Test",position:0,work_ms:10000,rest_ms:5000,off_hand:false,notes:null}]}};let mounted=0;let rpcCalls=0;
 const client={auth:{getUser:async()=>({data:{user:{id:actorUserId}}})},rpc:async(name,args)=>{rpcCalls++;assert.equal(name,"can_act_for_training_session");assert.deepEqual(args,{p_session_id:input.sessionId});return options.capabilityError?{data:null,error:{message:"unavailable"}}:{data:options.canAct??!options.coach,error:null};},from(table){const q={select(){return q;},eq(){return q;},single(){return q;},limit(){return q;},order(){return q;},then(resolve){return Promise.resolve({data:options.unauthorized&&table==="training_sessions"?null:queries[table],error:options.unauthorized&&table==="training_sessions"?{}:null}).then(resolve);}};return q;}};
 const page=load("src/app/training/[sessionId]/page.tsx",{"@/lib/supabase/server":{createClient:async()=>client},"next/navigation":{notFound:()=>{throw Error("404");},redirect:()=>{throw Error("redirect");}},"next/link":{default:props=>React.createElement("a",props)},"@/components/workout/workout-player":{default:()=>{mounted++;return React.createElement("div",null,"Player");}},"@/components/workout/completed-workout-delivery":{default:()=>null},"@/lib/training-session-prescription":prescriptionMapper});
 return {render:async()=>renderToStaticMarkup(await page.default({params:Promise.resolve({sessionId:input.sessionId})})),mounted:()=>mounted,rpcCalls:()=>rpcCalls};
}
test("coach session stays read-only and never mounts player",async()=>{const p=pageSetup({coach:true});assert.ok((await p.render()).includes("Read-only workout view"));assert.equal(p.mounted(),0);});
test("ACT capability, rather than actor equality, mounts child training for guardian",async()=>{const parent=id(501),child=id(502),p=pageSetup({actorUserId:parent,athleteId:child,athleteUserId:null,canAct:true});assert.ok((await p.render()).includes("Player"));assert.equal(p.mounted(),1);assert.equal(p.rpcCalls(),1);assert.notEqual(parent,child);});
test("VIEW-only or capability-error page remains documented and never mounts recovery player",async()=>{for(const options of [{actorUserId:id(511),athleteId:id(512),athleteUserId:null,canAct:false},{actorUserId:id(521),athleteId:id(522),athleteUserId:null,capabilityError:true}]){const p=pageSetup(options);assert.ok((await p.render()).includes("Read-only workout view"));assert.equal(p.mounted(),0);}});
test("completed athlete session never mounts active player",async()=>{const p=pageSetup({completed:true});assert.ok((await p.render()).includes("Workout completed"));assert.equal(p.mounted(),0);});
test("unrelated user cannot start another athlete's session",async()=>{const p=pageSetup({coach:true,unauthorized:true});await assert.rejects(p.render(),/404/);assert.equal(p.mounted(),0);});
async function hookHarness() {
 const actorUserId=id(next++),athleteId=id(next++),sessionId=id(next++);const props={...input,actorUserId,athleteId,sessionId};
 const values=[],effects=[],refs=[];let slot=0;const listeners=new Map();const docListeners=new Map();let authCallback;
 const oldWindow=globalThis.window,oldDocument=globalThis.document,oldFetch=globalThis.fetch;
 const requests=[];
 globalThis.window={addEventListener:(n,fn)=>listeners.set(n,fn),removeEventListener:()=>{},setInterval:()=>0};
 globalThis.document={visibilityState:"visible",addEventListener:(n,fn)=>docListeners.set(n,fn),removeEventListener:()=>{}};
 globalThis.fetch=async(_url,options)=>{requests.push(JSON.parse(options.body));return new Response("{}",{status:503});};
 const client={auth:{getUser:async()=>({data:{user:{id:actorUserId}},error:null}),onAuthStateChange:fn=>{authCallback=fn;return {data:{subscription:{unsubscribe(){}}}};}}};
 const fakeReact={useState:v=>{const i=slot++;values[i]=typeof v==="function"?v():v;return [values[i],next=>{values[i]=next;}];},useRef:v=>{const i=slot++;refs[i]={current:v};return refs[i];},useCallback:fn=>fn,useEffect:fn=>effects.push(fn)};
 const hook=load("src/components/workout/use-workout-session.ts",{react:fakeReact,"@/lib/supabase/client":{createClient:()=>client},"@/lib/workout-attempt-finalization":finalization,"@/lib/workout-session-state":state,"@/lib/workout-session-storage":storage});
 const controller=hook.useWorkoutSession(props);const cleanups=effects.map(fn=>fn());
 await new Promise(resolve=>setTimeout(resolve,5));
 return {props,controller,read:()=>values[0],visibility:state=>{globalThis.document.visibilityState=state;docListeners.get("visibilitychange")();},auth:authCallback,requests,bundle:()=>storage.mutateBundle(athleteId,()=>{}),settle:()=>new Promise(resolve=>setTimeout(resolve,10)),close:()=>{cleanups.forEach(fn=>fn?.());globalThis.window=oldWindow;globalThis.document=oldDocument;globalThis.fetch=oldFetch;}};
}
test("visibility before Begin emits nothing",async()=>{const h=await hookHarness();try{h.visibility("hidden");await h.settle();assert.equal((await h.bundle()).outbox.length,0);}finally{h.close();}});
test("listener deduplicates hidden/visible and keeps deadlines independent",async()=>{const h=await hookHarness();try{await h.controller.run("begin");const deadline=h.read().phaseStartedAt;h.visibility("hidden");h.visibility("hidden");await h.settle();h.visibility("visible");await h.settle();const all=(await h.bundle()).outbox.map(x=>x.event.event_type);assert.equal(all.filter(x=>x==="page_hidden").length,1);assert.equal(all.filter(x=>x==="page_visible").length,1);assert.equal(h.read().phaseStartedAt,deadline);assert.equal(h.read().pausedAt,null);}finally{h.close();}});
test("listener ignores visibility after canonical finalization",async()=>{const h=await hookHarness();try{await h.controller.run("begin");await h.controller.run("finalize");h.visibility("hidden");await h.settle();assert.equal((await h.bundle()).outbox.some(x=>x.event.event_type==="page_hidden"),false);}finally{h.close();}});
test("rapid stale skip clicks cannot skip two phases",async()=>{const h=await hookHarness();try{await h.controller.run("begin");const expected={index:0,phase:"work",paused:false};await Promise.all([h.controller.run("skip",expected),h.controller.run("skip",expected)]);assert.equal(h.read().phase,"rest");assert.equal((await h.bundle()).outbox.filter(x=>x.event.event_type==="exercise_skipped").length,1);}finally{h.close();}});
test("account change stops old checkpoint mutations",async()=>{const h=await hookHarness();try{await h.controller.run("begin");const n=(await h.bundle()).outbox.length;h.auth("SIGNED_IN",{user:{id:id(999)}});await h.controller.run("pause");assert.equal((await h.bundle()).outbox.length,n);}finally{h.close();}});
test("duplicate Begin recovers the stored prescription and attempt",async()=>{const h=await hookHarness();try{await h.controller.run("begin");const attempt=h.read().attemptId;h.props.steps=[step({durationSeconds:999})];await h.controller.run("begin");assert.equal(h.read().attemptId,attempt);assert.equal(h.read().steps[0].durationSeconds,10);assert.equal((await h.bundle()).outbox.filter(x=>x.event.event_type==="workout_started").length,1);}finally{h.close();}});
test("attempt metrics keep prescription elapsed pause and work distinct",()=>{let cp=command(begin().checkpoint,"pause",3000).checkpoint;const m=state.attemptMetrics(cp,start+5000);assert.equal(m.prescribedMs,35000);assert.equal(m.elapsedMs,5000);assert.equal(m.explicitPauseMs,2000);assert.equal(m.workProgressMs,3000);cp=command(cp,"resume",5000).checkpoint;assert.equal(state.attemptMetrics(cp,start+6000).workProgressMs,4000);});
test("checkpoint identity/version validation rejects foreign or corrupt state",()=>{const cp=begin().checkpoint;const bundle={checkpoints:{[input.sessionId]:cp}};assert.equal(storage.storedCheckpoint(bundle,input.athleteId,input.sessionId),cp);assert.throws(()=>storage.storedCheckpoint(bundle,id(999),input.sessionId));cp.version=999;assert.throws(()=>storage.storedCheckpoint(bundle,input.athleteId,input.sessionId));});
